name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  # This specifies Python 3.11.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest  # If you are using pytest for testing

    - name: Run tests
      run: |
        pytest test_main.py
